### ISSUE TITLE
show address balance

### ISSUE THREAD

**Issue by AndySchroder** [miohtama/bitcoinaddress.js#2]
It would be awesome if you could have the ability show the address balance in this tool. Both confirmed, as well as unconfirmed transactions. This could allow a small merchant to have a very easy point of sale tool (for currently low volume bitcoin sales), just stored in a single HTML file with some public addresses hard coded into the file stored locally on their PC. They could have 10 or 20 addresses available, using one per sale. Then at the end of the day manually sweep all funds to another address using the computer that stores the private keys, so that all 10 or 20 have a fresh balance again.

**Comment by miohtama** [comment]
Woops. I have missed these issues before, so sorry for the late reply.

As far as I know there is no public JavaScript API to check address balances.

http://bitcoin.stackexchange.com/a/30260/5464
